version: 0.2
phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
     - echo Build started on `date`
      - chmod +x ./gradlew
      - ./gradlew build
artifacts:
  files:
    - /app/build/outputs/apk/release/app-release.apk
  discard-paths: yes
