version: 0.2
phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
     - echo Build started on `date`
      - chmod +x ./gradlew
      - ./gradlew assembleRelease --stacktrace
artifacts:
  files:
    - “**/*”
  discard-paths: no
  base-directory: build