version: 0.2
phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - cd /android
      - echo Build started on `date`
      - chmod +x ./gradlew
      - ./gradlew assembleRelease
artifacts:
  files:
    - /app/build/outputs/apk/debug/*.apk
  discard-paths: yes
